### ISSUE TITLE
[Device] Is it possible to automate testing of multiple devices at once?

### ISSUE THREAD

**Issue by hosan07** [dogu-team/gamium#12]
I am planning to use Gamium to automate app testing on Android and iOS devices in Unity. Is it possible to automate testing of multiple devices at once?

**Comment by yowpark** [comment]
Hello. Thank you for your inquiry. Currently, if you run one gamium script, the test will be conducted on one device. In order to automate testing on multiple devices, I think you need to write a script so that you can run multiple gamium scripts (python, typescript) on multiple devices and link it to the CI/CD system.
